[project]
name = "activation_steering"
version = "0.1.0"
description = "General-purpose activation steering library"
authors = ["Bruce W. Lee <bruce.lee1@ibm.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tasks]
# Install the current package in editable mode
install = "pip install --no-build-isolation --no-deps -e ."

[dependencies]
python = ">=3.10"
numpy = ">=1.26.4"
scikit-learn = ">=1.5.0"
pytorch = ">=2.3.1"
transformers = ">=4.41.2"
accelerate = ">=0.32.0"
tqdm = ">=4.66.4"
rich = ">=13.7.1"
matplotlib = ">=3.9.0"
einops = ">=0.8.0"
pip = "*"

[pypi-dependencies]
gguf = ">=0.6.0"
